name: Build and Push

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: build-latest 
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/lufi
        always_pull: true
        tags: latest
        build_args: LUFI_VERSION=master
        add_git_labels: true
        push: true
    
    - name: build-0.04.6
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/lufi
        tags: 0.04.6
        always_pull: true
        build_args: LUFI_VERSION=0.04.6
        add_git_labels: true
        push: true